name: zezis_widget
description: Functions/Widget/Alerts/Dialogs in a customized way and with easy dependency management.

version: 0.3.14+4
repository: https://github.com/joseaugustoaquino/zezis_widget
homepage: https://github.com/joseaugustoaquino

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter: 
    sdk: flutter

  get: ^4.7.2
  intl: ^0.20.2
  meta: ^1.16.0
  equatable: ^2.0.7
  google_fonts: ^6.2.1
  pointer_interceptor: ^0.10.1+2
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/gifs/