name: zezis_widget
description: Funções/Widget/Alertas/Dialogos de forma customizada e com fácil gerenciamento de dependencias.

version: 0.0.1
repository: https://github.com/joseaugustoaquino/zezis_widget

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0