name: zezis_widget
description: Functions/Widget/Alerts/Dialogs in a customized way and with easy dependency management.

version: 0.3.8+1
repository: https://github.com/joseaugustoaquino/zezis_widget
homepage: https://github.com/joseaugustoaquino

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter: 
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  get: ^4.6.6
  intl: ^0.19.0
  meta: ^1.12.0
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  pointer_interceptor: ^0.10.1+2
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/gifs/