name: zezis_widget
description: Functions/Widget/Alerts/Dialogs in a customized way and with easy dependency management.

version: 0.2.33
repository: https://github.com/joseaugustoaquino/zezis_widget
homepage: https://github.com/joseaugustoaquino

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  intl: ^0.18.1
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  libphonenumber_plugin: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/gifs/
    